apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-08-30T21:52:51Z"
  labels:
    com.docker.service.id: example-app-redis
    com.docker.service.name: redis
    com.docker.stack.namespace: example-app
  name: redis
  namespace: default
  ownerReferences:
  - apiVersion: compose.docker.com/v1alpha3
    blockOwnerDeletion: true
    controller: true
    kind: Stack
    name: example-app
    uid: a48273a1-ab29-4f93-8875-fb71b4346a21
  resourceVersion: "136980"
  selfLink: /api/v1/namespaces/default/services/redis
  uid: 1ee03004-aee7-45bd-9128-b962ed2d1635
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    protocol: TCP
    targetPort: 55555
  selector:
    com.docker.service.id: example-app-redis
    com.docker.service.name: redis
    com.docker.stack.namespace: example-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
