apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-08-30T21:52:51Z"
  labels:
    com.docker.service.id: example-app-web
    com.docker.service.name: web
    com.docker.stack.namespace: example-app
  name: web-published
  namespace: default
  ownerReferences:
  - apiVersion: compose.docker.com/v1alpha3
    blockOwnerDeletion: true
    controller: true
    kind: Stack
    name: example-app
    uid: a48273a1-ab29-4f93-8875-fb71b4346a21
  resourceVersion: "137012"
  selfLink: /api/v1/namespaces/default/services/web-published
  uid: b50c0621-0d1a-412c-bd81-49e0da6d76f4
spec:
  clusterIP: 10.108.100.46
  externalTrafficPolicy: Cluster
  ports:
  - name: 5000-tcp
    nodePort: 31153
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    com.docker.service.id: example-app-web
    com.docker.service.name: web
    com.docker.stack.namespace: example-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
